---
title: "Untitled"
author: "Juliano Palacios"
date: "2023-12-04"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(MyFunctions)

my_lib(
  c(
    "tidyverse",
    "sf"
  )
)

```



```{r}

eez <- my_sf("SAU",simple = 0.5)

rfmo_files <- as.data.frame( list.files(my_path("R", "Per_change_realm_rfmo")))
colnames(rfmo_files) <- "x"

rfmo_files <- as.data.frame(str_sub(rfmo_files$x, 1,6))
colnames(rfmo_files) <- "x"

old_files <- as.data.frame( x =list.files(my_path("R", "Straddling_rfmo")))
colnames(old_files) <- "x"

old_files <- as.data.frame(str_sub(old_files$x, 1,6))
colnames(old_files) <- "x"

anti_join(old_files,rfmo_files) %>% 
  # View() %>% 
  mutate(taxon_key = as.integer(x)) %>% 
  left_join(exploited_spp) %>% 
  View()




exploited_spp <- my_data("dbem_species")


Distpath <- my_path("G", "FishForVisa/Data/Distribution/")

CoorG <- read.csv("~/Library/CloudStorage/OneDrive-UBC/Data/FishForVisa/Data/Spatial/coordinates_gab.csv") %>% 
  mutate(index = seq(1,259200,1))

dbem_coords <- my_data("dbem_coords")


Spp <- 600024 # Common shrimp


distribution_map <- function(Spp){
  
  # Save figures
  taxon_name <- exploited_spp %>% 
    filter(taxon_key %in% Spp) %>% 
    pull(common_name)
  
  # Get data source
  Models_List <- c(paste(Distpath,"SAU_Distribution/DIST_GOOD_SP_",Spp,".mat",sep =""),
                   paste(Distpath,"Occurence/OCCURENCE_JULIANO_",Spp,".mat",sep=""),
                   paste(Distpath,"ENM/ENM_JULIANO_",Spp,".mat",sep="")
  )
  
  
  # Load Data
  Load <- lapply(Models_List, FUN=R.matlab::readMat, na.strings=0)
  
  sppdist <- as.data.frame(bind_cols(Load)) %>% 
    mutate(
      INDEX = seq(1,259200,1),
      TaxonKey = Spp
    )
  colnames(sppdist) <- c("SAU_D","Occ","ENM","index","TaxonKey")
  
  # SAU cartch data
  File_Name <- paste("SAU_data_per_species/CATCH_SP_")
  SppPath <- paste(Distpath,File_Name,Spp,".mat",sep="")
  
  SAU_C_data <- as.data.frame(R.matlab::readMat(SppPath)) %>% 
    select(CATCH.1:CATCH.65) %>% 
    mutate(index = seq(1,259200,1)) %>% 
    gather("Year","Catch",CATCH.56:CATCH.65) %>% # Last 10 years of data
    group_by(index) %>% 
    summarise(SAU_C = mean(Catch,na.rm=T))
  
  
  # Make map of distributions
  
  dist_map <- sppdist %>% 
    left_join(SAU_C_data,
              by = "index") %>% 
    select(TaxonKey,index,everything()) %>% 
    left_join(CoorG,
              by = "index") %>% 
    gather("Model","Value",SAU_D:SAU_C) %>%
    filter(Value > 0) %>% 
    ggplot() +
    geom_tile(
      aes(
        x = Longitude,
        y = Latitude
      ),
      fill = "yellow"
    ) +
    facet_wrap(~Model) +
    my_land_map(fill = "grey70", color = "grey70") +
    geom_sf(data = eez, aes(), fill = "lightblue") +
    ggtitle(paste("Original distributions for",taxon_name)) +
    my_ggtheme_m()
  
  map_name <- paste0(taxon_name,"_",Spp,".png")
  
  ggsave(filename = my_path("R","Distributions",name = map_name),
         plot = dist_map,
         height = 7,
         width = 10
         )
  
}


```


```{r}
distribution_map(600024)

mclapply(stra_spp, distribution_map)

```

