---
title: "Addressing shifts in the distribution of internationally shared marine fish stocks for achieving a sustainable deep-sea blue economy"
author: "Juliano Palacios-Abrantes"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(MyFunctions)

packages <- c(
  "readxl", # Read dataframe
  "data.table", # Read dataframe (Fast!)
  "tidyverse",
  "sf"
)

my_lib(packages)

# Fix new updates of sf package
sf::sf_use_s2(use_s2 = FALSE)

source("./functions/get_results.R")
```

# Global data

```{r}

dbem_spp <- my_data("dbem_species")

fb_species <- read_excel("~/Library/CloudStorage/OneDrive-UBC/Data/Species/updated_data/sau_updated_data/FB_Species.xlsx")


slb_species <- read_excel("~/Library/CloudStorage/OneDrive-UBC/Data/Species/updated_data/sau_updated_data/SLB_Species.xlsx")

# Join data
suppressWarnings(
  spp_deep <- bind_rows(fb_species,
                        slb_species) %>% 
    mutate(taxon_name = paste(Genus,Species)) %>% 
    select(taxon_name,DepthRangeShallow,DepthRangeDeep) %>% 
    right_join(dbem_spp) %>% 
    filter(is.na(DepthRangeDeep) | DepthRangeDeep> 200)
)

World_map_dat <- Matching_names %>% 
  group_by(sau_fishing_entity,fishing_entity_id,iso_a3) %>% 
  summarise(n=n()) %>% 
  select(-n) 

World_map <- rnaturalearth::ne_countries(scale = 'large', returnclass = c("sf")) %>%
  clean_names() %>% 
  select(iso_a3,sovereignt,sov_a3,name,name_long,region_wb,continent,geometry) %>% 
  st_transform(crs = "+proj=eck4") %>%
  # st_transform(crs = 4326) %>% # 4326
  mutate(iso_a3 = ifelse(sovereignt == "Norway","NOR",
                         ifelse(name == "France","FRA",
                                iso_a3)
  )
  ) %>% 
  left_join(World_map_dat,
            by = "iso_a3")


World_eez_sf <- my_sf("SAU")

```
# Functions

```{r}
PropChange <- function(taxon_list,links="NA", top = F){
  
  eez <- EEZProp(taxon_list,links, top = top)
  
  proportion_change <- eez %>% 
    gather("variable","value",n_stock:n_per) %>% 
    spread(time_step,value) %>% 
    mutate_at(vars(
      "per_early" = early,
      "per_mid" = mid
    ),
    funs(ifelse(variable == "n_per",.,round(((.-historical)/(abs(historical)))*100,2) # original
    )
    )
    )
  
  return(proportion_change)
  
}

EEZProp <- function(taxon_list,links="NA",top = F){
  
  spp <- bind_rows(
    lapply(taxon_list,SummaryProp,links,top = top)
  )
  
  
  if(links == "y"){
    
    # Percentage of SSR stocks changing
    n_ssr <- spp %>% 
      group_by(eez_name,time_step) %>% 
      summarise(
        # n_spp = length(unique(taxon_key)),
        n_stock = n(),
      ) %>% 
      spread(time_step,n_stock) %>% 
      mutate_at(vars(early,mid),
                .funs = ~(./historical)*100
      ) %>% 
      select(-historical) %>%
      gather("time_step","n_per",early:mid)
    
    # Min, max and median change per eez_name and neighbor
    eez_summary <- spp %>% 
      group_by(eez_name,eez_neighbour,time_step) %>% 
      summarise(
        # n_spp = length(unique(taxon_key)),
        n_stock = n(), # Number of shifting stocks
        min_eez = min(mean_spp, na.rm=T), #minimum proportion across all shifting stocks
        max_eez = max(mean_spp, na.rm=T), # maximum proportion across all shifting stocks
        sd_eez = sd(mean_spp, na.rm=T), # for some weird reason it wont work if the order is fliped
        mean_eez = median(mean_spp,na.rm=T) # mean proportion across all shifting stocks
      ) %>% 
      select(eez_name:max_eez,mean_eez,sd_eez,n_stock) %>% 
      left_join(n_ssr)
    
  }else{
    
    eez_summary <- spp %>% 
      group_by(eez_name,time_step) %>% 
      summarise(
        # n_spp = length(unique(taxon_key)),
        n_stock = n(),
        min_eez = min(mean_spp, na.rm=T),
        max_eez = max(mean_spp, na.rm=T),
        sd_eez = sd(mean_spp, na.rm=T), # for some weird reason it wont work if the order is fliped
        mean_eez = mean(mean_spp,na.rm=T)
      ) %>% 
      select(eez_name:max_eez,mean_eez,sd_eez,n_stock)
    
    
  }
  
  return(eez_summary)
  
}


SummaryProp <- function(taxon_key,links="NA", top = F){
  
  if(top == T){
    # Reads taxon data
    proportion_data <- fread(paste(my_path("G","EmergingFish/Results/Proportion_2005_fix"),"proportion_",taxon_key,".csv", sep="")) %>% 
      filter(!is.na(eez_neighbour)) %>% 
      rename(sf_eez_name = eez_name) %>% 
      left_join(Matching_names) %>% 
      semi_join(top_stocks_per_country) %>% 
      select(
      1:4,
      ensemble_mean = catch_proportion_temp_mean_ensemble_mean,
      ensemble_sd = catch_proportion_temp_mean_ensemble_sd) %>% 
      rename(eez_name = sf_eez_name)
    
  }else{
  
  # Reads taxon data
  proportion_data <- fread(paste(my_path("G","EmergingFish/Results/Proportion_2005_fix"),"proportion_",taxon_key,".csv", sep="")) %>% 
    filter(!is.na(eez_neighbour)) %>% 
    select(
      1:4,
      ensemble_mean = catch_proportion_temp_mean_ensemble_mean,
      ensemble_sd = catch_proportion_temp_mean_ensemble_sd)
  
  }
  
  # Identify SSR treshold for natural spatial variability of the stock
  proportion_tresh <- proportion_data %>% 
    filter(time_step == "historical") %>% 
    mutate(
      top_tresh = ensemble_mean+(2*ensemble_sd), # two s.d.
      low_tresh = ensemble_mean-(2*ensemble_sd) # two.s.d
    ) %>% 
    select(taxon_key:eez_neighbour,top_tresh:low_tresh) %>% 
    left_join(proportion_data) %>% 
    # Only keeps change if surpasses treshold
    mutate(
      over_tresh = ifelse(time_step != "historical" & ensemble_mean > top_tresh | ensemble_mean < low_tresh,"keep",
                          ifelse(time_step == "historical","keep","drop")
      )
    ) %>% 
    # filter(time_step !="historical" | over_tresh == "keep") %>%
    filter(over_tresh == "keep") %>%
    select(-top_tresh,-low_tresh)
  
  if(links == "y"){
    # summarizes by country and neighbour
    country_summary <- proportion_tresh %>% 
      group_by(taxon_key,eez_name,eez_neighbour,time_step) %>% 
      summarise(
        mean_spp = mean(ensemble_mean, na.rm = T) # average spp change from all countries sharing
      ) %>% 
      filter(!is.na(mean_spp))
    
  }else{
    # summarizes by country
    country_summary <- proportion_tresh %>% 
      group_by(taxon_key,eez_name,eez_neighbour,time_step) %>% 
      summarise(
        mean_spp = mean(ensemble_mean,na.rm=T) # average spp change from all countries sharing that speceies
      ) %>% 
      filter(!is.na(mean_spp))
  }
  
  return(country_summary)
}


```

# Transboundary stocks data

```{r}

# Transboundary species and their sharing EEZs (see Palacios-Abrantes et al; FishForVisa)
deep_transboundary_spp <- my_path("G", extra_path = "EmergingFish/Data/Species/", name="Transboundary_spp.csv", read = TRUE) %>% 
  clean_names() %>% 
  group_by(taxon_key) %>% 
  tally() %>% 
  left_join(spp_deep) %>% 
  filter(!is.na(taxon_name))

# Complete missing
# Get species where Updated FishBase data is not available
missing_trans <- deep_transboundary_spp %>% 
  filter(is.na(DepthRangeDeep))

# List my species
lh_data <- bind_rows(
  lapply(list.files(my_path("Spp","TaxonDataC"),full.names = T), read.delim)
)

# Get data from personal dataset
missing_spp_data <- lh_data %>% 
  gather("name","value",2:944) %>% 
  mutate(
    taxon_key = as.numeric(str_sub(name,2,7))
         ) %>% 
  # left_join(missing_trans) %>% 
  filter(
    taxon_key %in% missing_trans$taxon_key,
         Taxonkey %in% c("MaxDepth","MinDepth"),
         !is.na(value)
         ) %>% 
  mutate(value = as.numeric(value)) %>% 
  spread(Taxonkey,value) %>% 
  select(taxon_key, DepthRangeShallow = MinDepth, DepthRangeDeep = MaxDepth)


# Final deep_species
deep_transboundary_spp_clean <- deep_transboundary_spp %>% 
  bind_rows(missing_spp_data) %>% 
  filter(!is.na(DepthRangeDeep),
         DepthRangeDeep >= 200,
         DepthRangeDeep != 9999,
         ) %>% 
  select(taxon_key,max_depth = DepthRangeDeep, min_depth = DepthRangeShallow) %>% 
  left_join(dbem_spp)


Transboundary_spp <- my_path("G", extra_path = "EmergingFish/Data/Species/", name="Transboundary_spp.csv", read = TRUE) %>% 
  filter(taxon_key %in% deep_transboundary_spp_clean$taxon_key)

```



```{r}


# Neighbour list and their respective id (see chunk 3)
Neighbours <- my_path("G", extra_path = "EmergingFish/Data/Spatial/", name="Neighbours_eez_id.csv", read = TRUE)


all_results <- list()

# List of taxon to run 
taxon_list <- deep_transboundary_spp_clean %>% 
  pull(taxon_name) %>% 
  unique()


# alphaid
# ------------------------------------------- #
### Estimate number of transboundary stocks ###
# ------------------------------------------- #

n_stock <-
  Transboundary_spp %>% 
  left_join(Neighbours,
            by = c("eez_name", "eez_neighbour")) %>% 
  group_by(neighbour_id) %>%
  summarise(n_stock = length(unique(taxon_key))) %>%
  # View()
  group_by() %>% 
  summarise(t_trans_stocks = sum(n_stock)) %>% 
  pull(t_trans_stocks) # 373


ssr_data <- read_csv("~/Library/CloudStorage/OneDrive-UBC/Data/EmergingFish/Results/ssr_data.csv") 

# Clean names to match data
Matching_names <- my_path("G","Spatial/SAU", "sau_matching_names.csv", read = T) %>% 
  rename(eezid = eez_id)

Taxon_list_emer <- list.files(my_path("G",extra_path = "/EmergingFish/Results/Emergence_2005"))

# clean names for function
Taxon_list_emer <- gsub("_.*","",Taxon_list_emer) 

# Filter out fish
# Filter paths that have distributions
Taxon_list_emer <- Taxon_list_emer[grepl(paste(deep_transboundary_spp_clean$taxon_key, collapse = "|"), Taxon_list_emer)]


Paths <- paste(my_path("G",extra_path = "/EmergingFish/Results/Emergence_2005"),Taxon_list_emer,"_emergence.txt",sep="")

# Load all sp in one table
Eme_Res <- bind_rows(lapply(Paths, fread)) %>% 
  filter(
    n_ens == 10
  ) %>% 
  left_join(Neighbours,
            by = c("eez_name","eez_neighbour")
  ) %>% 
  rename(sf_eez_name=eez_name) %>% 
  left_join(Matching_names,
            by=  "sf_eez_name") %>% 
  clean_names() %>% 
  mutate(tresh = str_to_lower(tresh)) %>% 
  filter(tresh == "tresh_two")

# Get taxon list
Taxon_list <- list.files(my_path("G","EmergingFish/Results/Proportion_2005_fix"))

# clean names for function
Taxon_list <- gsub(".*_","",Taxon_list) 

# clean names for function
Taxon_list <- gsub(".csv","",Taxon_list) 

# Filter paths that have distributions
taxon_list_prop <- Taxon_list[grepl(paste(deep_transboundary_spp_clean$taxon_key, collapse = "|"), Taxon_list)]

suppressMessages(
  prop_results <- PropChange(taxon_list_prop, links="y") %>%
    filter(!is.na(eez_neighbour)) %>%
    mutate(per_mid_plot =ifelse(per_mid >= 100, 100,
                                ifelse(per_mid <= -100,-100,per_mid)
    ),
    per_early_plot =ifelse(per_early >= 100, 100,
                           ifelse(per_early <= -100,-100,per_early)
    )
    )
)

```


```{r}

spp_complete <- list.files(my_path("R","Per_change_realm_rfmo/"))
straddling_spp <- str_replace(spp_complete,"\\_.*","")

partial_straddling_df <- bind_rows(
  lapply(straddling_spp,GetResults, type = "strad")
  ) %>% 
  rename(realm_name = realm
         ) %>% 
  # Filter only deep species 
  filter(taxon_key %in% deep_transboundary_spp_clean$taxon_key)

length(unique(partial_straddling_df$taxon_key))# 86 

# Get straddling stocks
prop_data_esm <- bind_rows(
  lapply(unique(partial_straddling_df$taxon_key),GetResults, type = "prop")
  ) %>%
  # View()
  # Include area index info
  left_join(partial_straddling_df,
            by = c("taxon_key","rfmo_name","realm_name")
        ) %>% 
  filter(area_rfmo > 10,
         area_rfmo < 90) %>% 
  # Remove species not present in high seas
  filter(
    low_tresh != 0 &
      mean != 0 &
      top_tresh != 0,
    low_tresh != 100 &
      mean != 100 &
      top_tresh != 100
           ) %>% 
  left_join(deep_transboundary_spp_clean) 


prop_data_strad <- prop_data_esm %>%
  # Re- estimate change with average of all ESMs
  group_by(taxon_key,taxon_name,common_name,rcp,period,rfmo_name,realm_name) %>% 
  summarise_at(
    .vars = c("low_tresh","mean","top_tresh"),
    .funs = mean,
    na.rm = T) %>% 
  mutate(change = ifelse(mean > top_tresh,"gain",
                               ifelse(mean < low_tresh,"lost","same")
        )
  )


# EEZ list and their centroid of distribution (see chunk 3)
eez_centroid <- my_path("Spa", extra_path = "SAU/", name="eez_centroids.csv", read = TRUE)



sau_data <-fread(paste(my_path("G","EmergingFish/Data/"),"SAU/sau_catch_value_country_taxon_JEPA.csv", sep ="")) %>%
  clean_names() %>% 
  # Remove high seas and 207 and 208 that are unknown
  filter(!fishing_entity_id %in% c(213,223)) %>%  # 207,208
  # Allocate catch of islands to UK
  mutate(fishing_entity_id = ifelse(fishing_entity_id %in% c(219,220), 183,fishing_entity_id)) %>% 
  # Convert to 2019 real USD
  mutate(values = 1.16 * value) %>%
  # Average 10 years of data
  group_by(fishing_entity_id,taxon_key) %>% 
  summarise_at(c("catch","value"),
               mean,na.rm=T) %>% 
  gather("variable","value",catch:value)


# --------------- #
# Load shapefiles for figures
# --------------- #





```

# Transboundary stocks Results

```{r}
# Global estimates
Eme_Res %>% 
  filter(emerging_yr >= 2030) %>% 
  group_by(tresh,neighbour_id) %>% 
  summarise(
    emerging_stocks = length(unique(taxon_key))
  ) %>% 
  group_by(tresh) %>% 
  summarise(
    emerging_stocks = sum(emerging_stocks),
    prop_total = (emerging_stocks/n_stock)*100,
  )

```
```{r}
# Per EEZs
Eme_Res %>% 
  # group_by() %>% 
  # summarise(meann_y = mean(emerging_yr,na_rm = T))
  group_by(sf_eez_name,eez_neighbour) %>% 
  summarise(
    n_total = n(),
    min_y = min(emerging_yr,na_rm = T),
    meann_y = mean(emerging_yr,na_rm = T)
  ) %>% 
  arrange(desc(n_total)) 

```




```{r}
prop_data %>% 
  group_by(rcp,period,change) %>%
  tally() %>% 
  mutate(
    change_b = ifelse(change == "same","same","change")
  ) %>% 
  group_by(rcp,period,change_b) %>%
  summarise(
    n_change = sum(n)
  )
```

## Accumulative figure

```{r}

n_eez <- length(unique(Eme_Res$sf_eez_name))
selected_tresh <- "tresh_two"

stock_d <-  
  Eme_Res %>% 
  left_join(Neighbours) %>% 
  # distinct(taxon_key,neighbour_id, .keep_all = TRUE) %>% 
  group_by(taxon_key,neighbour_id,tresh) %>% 
  summarise(
    taxon_emer = min(emerging_yr)
  ) %>% 
  group_by(taxon_emer,tresh) %>% 
  summarise(
    n_tax = n()
  ) %>% 
  group_by(tresh) %>% 
  mutate(
    com_sum = cumsum(n_tax),
    level = "stock"
  )

eez_d <-  Eme_Res %>% 
  left_join(Neighbours) %>% 
  filter(n_ens == 10) %>% 
  # distinct(eez_name,neighbour_id, .keep_all = TRUE) %>% 
  group_by(sf_eez_name,tresh) %>% 
  summarise(
    taxon_emer = min(emerging_yr)
  ) %>% 
  group_by(taxon_emer,tresh) %>% 
  summarise(
    n_tax = n()
  ) %>% 
  group_by(tresh) %>% 
  mutate(
    com_sum = cumsum(n_tax),
    level = "eez"
  )

# max(eez_d$com_sum)

# Plot Data
plot_data <- stock_d %>% 
  bind_rows(eez_d) %>% 
  filter(tresh != "NA") %>% 
  mutate(
    # total = ifelse(level == "stock",length(unique(Eme_Res$taxon_key)),length(unique(Eme_Res$sf_eez_name))),
    total = ifelse(level == "stock",n_stock,n_eez),
    per = com_sum/total*100
  ) %>% 
  gather("metric","value",com_sum,per) #%>% 


# Manually include rest of data until 2100
cont_eez <- plot_data %>% 
  filter(level == "eez") %>% 
  arrange(taxon_emer) %>% 
  slice(1:24) %>%
  select(-1) %>% 
  arrange(metric) %>% 
  mutate(
    value = ifelse(metric == "per",81,228),
    taxon_emer = c(seq(2088,2099,1),seq(2088,2099,1))
  )

plot_data <- plot_data %>% 
  bind_rows(cont_eez) %>% 
  mutate(
    my_facet = ifelse(metric == "per","Percentage (%)","Cumulative sum (n stocks)"),
    label = ifelse(total == max(stock_d$com_sum),"Total number of emerging stocks","Total number of EEZs")
  )


dashed_lines <- tibble(
  x = c(2030
        # ,2050,2070),
  ),
  label = c("UN 2030 Agenda"
            # ,"Mid range shift   ","Late range shift   "
  )
)




# Percentage plot
ggplot() +
  geom_area(data = subset(plot_data, level == "eez" & my_facet == "Percentage (%)"),
            aes(
              x = as.numeric(taxon_emer),
              y = value,
              fill = level
            ),
            size=0.5,
            colour="black"
  ) + 
  geom_area(data = subset(plot_data, level == "stock" & my_facet == "Percentage (%)"),
            aes(
              x = as.numeric(taxon_emer),
              y = value,
              fill = level
            ),
            size=0.5,
            colour="black"
  ) + 
  # Add dashed lines and labels
  geom_vline(
    data = dashed_lines,
    aes(
      xintercept = x
    ),
    linetype="dashed",
    color = "grey"
  ) +
  geom_text(data = dashed_lines,
            aes(
              x = x-4,
              y = 14,
              label = label
            ),
            size = 4,
            color = "white",
            angle = 90
  ) +
  scale_y_continuous("Cumulative proportion of the total (%)",
                     expand = c(0,0)
  ) +
  scale_x_continuous("",
                     breaks = seq(2000,2100,20),
                     limits = c(2005,2100),
                     label = seq(2000,2100,20)
  ) +
  my_ggtheme_p(leg_pos = "right") +
  scale_fill_viridis(discrete = T,
                     begin = 0.1,
                     end = 0.7,
                     labels = c("EEZs","Stocks")
  )+theme(
    axis.ticks.x = element_line()
  ) 


```

## ToE Map

```{r emergence_map_data, eval = F}
# Per EEZs
Eez_d_hist <- Eme_Res %>% 
  group_by(eezid,sau_fishing_entity,tresh) %>% 
  # summarise(n_tax = length(unique(taxon_key))) %>% 
  summarise(
    mean_yr = mean(emerging_yr,na.rm=T),
    sd_yr = sd(emerging_yr,na.rm=T),
    n_taxa = length(unique(taxon_key))
  ) %>% 
  gather("metric","value",mean_yr:n_taxa) %>% 
  # filter(metric != "n_taxa") %>% 
  mutate(
    reverse = abs(value-2100)  + 2000
  )


# Estimate the value (catch and USD) of emerging species
Eme_value_data <- Eme_Res %>% 
  group_by(sau_fishing_entity,fishing_entity_id,tresh,taxon_key) %>% 
  summarise(n()) %>% 
  left_join(sau_data,
            by = c("fishing_entity_id","taxon_key")) %>% 
  filter(!is.na(variable)) %>% 
  group_by(sau_fishing_entity,fishing_entity_id,tresh,variable) %>% 
  summarise(
    sum_value = sum(value,na.rm=T),
    n_taxa = length(unique(taxon_key)) 
  )


# Total value of each fishing nation

total_value <- sau_data %>% 
  group_by(fishing_entity_id,variable) %>% 
  summarise(tot_value= sum(value,na.rm=T))


value_map_data <- Eme_value_data %>% 
  left_join(total_value,
            by = c("fishing_entity_id","variable")) %>% 
  mutate(participation = (sum_value/tot_value)*100+2000)


# Per fishing entity

fish_d_hist <- Eme_Res %>% 
  group_by(sau_fishing_entity,tresh) %>% 
  # summarise(n_tax = length(unique(taxon_key))) %>% 
  summarise(
    value = length(unique(taxon_key))
  ) %>% 
  filter(!is.na(sau_fishing_entity))

world_map_nemer <- World_map %>%
  full_join(value_map_data,
            by = c("sau_fishing_entity","fishing_entity_id")
  ) %>% 
  filter(!is.na(participation)) %>% 
  sf::st_transform(crs = "+proj=eck4") 


# These are regions without transboundary species
grey_land <- World_map %>% 
  filter(!fishing_entity_id %in% Value_map_data$fishing_entity_id) %>% 
  filter(!sovereignt %in% c("Antarctica"))%>% 
  sf::st_transform(crs = "+proj=eck4") 


toe_map_data <- World_eez_sf %>% 
    left_join(Eez_d_hist,
              by = "eezid") %>% 
    filter(metric == "mean_yr")%>% 
    sf::st_transform(crs = "+proj=eck4") 

pal <- wes_palette("Zissou1", 100, type = "continuous")

map <- ggplot(toe_map_data) +
    geom_sf(
      aes(
        # fill = reverse #original map
        fill = value
      ),
      color =  "white",
      size = 0.1
    ) +
  geom_sf(data = World_map, aes(), fill = "grey70", color =  "grey30",size = 0.1) +
  my_ggtheme_m(leg_pos = "bottom") +
    theme(
    #   legend.box.margin = margin(t = -61,l = 180),
    #   legend.text = element_blank(),
    #   legend.background = element_blank(),
      legend.key.width = unit(5, "line")
    ) +
    scale_fill_gradientn("",
                         colours = rev(viridis(100)),
                         limits = c(2000,2100)
                         )
  # scale_fill_viridis_b("Average year of range shift",
                       # direction  = -1,
                       # limits = c(2000,2100)
                       # )

ggsave("toe_mapc.png",map,
       width = 10,
       height = 5)

```

## Prop results

```{r}
data_for_connection=function( dep_lon, dep_lat, arr_lon, arr_lat, group){
  inter <- gcIntermediate(c(dep_lon, dep_lat), c(arr_lon, arr_lat), n=50, addStartEnd=TRUE, breakAtDateLine=F)             
  inter=data.frame(inter)
  inter$group=NA
  diff_of_lon=abs(dep_lon) + abs(arr_lon)
  if(diff_of_lon > 180){
    inter$group[ which(inter$lon>=0)]=paste(group, "A",sep="")
    inter$group[ which(inter$lon<0)]=paste(group, "B",sep="")
  }else{
    inter$group=group
  }
  return(inter)
}



# Use a different palet between SSR and ToE
pal <- wesanderson::wes_palette("Zissou1",100,type = "continuous")

# Prepare data from results
Data <- prop_results %>% 
  # get coords for sources
  left_join(eez_centroid,
            by = "eez_name") %>%
  rename(source = eez_name,
         start_lon = longitude,
         start_lat = latitude,
         eez_name=eez_neighbour) %>% 
  # get coords for targets
  left_join(eez_centroid,
            by = "eez_name") %>%
  rename(target = eez_name,
         end_lon = longitude,
         end_lat = latitude) %>% 
  ungroup() %>% 
  # Plot miscs
  mutate(
    per_early = ifelse(is.na(per_early),0,per_early),
    per_mid = ifelse(is.na(per_mid),0,per_mid)
  ) %>% 
  drop_na()


# Get paths data
path_data <- Data %>% 
  filter(
    variable %in% c("mean_eez")
  )

data_ready_plot=data.frame()

for(i in c(1:nrow(path_data))){
  tmp=data_for_connection(path_data$start_lon[i], path_data$start_lat[i], path_data$end_lon[i], path_data$end_lat[i] , i)
  tmp$per_early_plot=path_data$per_early_plot[i]
  tmp$per_mid_plot=path_data$per_mid_plot[i]
  tmp$source=path_data$source[i]
  tmp$objective=path_data$target[i]
  data_ready_plot=rbind(data_ready_plot,tmp)
}

data_ready_plot <- data_ready_plot %>% 
  mutate(
    per_early = ifelse(per_early_plot >= 50,50,per_early_plot),
    per_mid = ifelse(per_mid_plot >= 50,50,per_mid_plot)) %>% 
  gather("time_step","percentage",per_early,per_mid)


time_toplot <- "per_mid"


sf_ready_plot <- data_ready_plot %>% 
  filter(time_step == time_toplot) %>% 
  st_as_sf(coords = c("lon", "lat")) %>% 
  st_set_crs(4326) %>% # to match shapefiles
  st_transform(crs = "+proj=eck4") 

# Get arrow data
arrows_data <- as.data.frame(st_coordinates(st_cast(sf_ready_plot,"POINT")$geometry)) %>% 
  bind_cols(data_ready_plot %>% 
              filter(time_step == time_toplot)
  )


# Get point data
point_data <- path_data %>% 
  gather("time_step","percentage",per_early:per_mid) %>% 
  filter(time_step == time_toplot,
         percentage <= 0) %>% 
  st_as_sf(
    coords = c("start_lon", "start_lat")
  ) %>% 
  select(source,target,geometry) %>% 
  st_set_crs(4326) %>% 
  st_transform(crs = "+proj=eck4")

#### Get the change of species 

n_trans_eez <- Transboundary_spp %>% 
  group_by(eez_name) %>% 
  summarise(
    # n_trans = unique(length(taxon_key))
    n_trans = n()
  )

# Estimate the percentage changing
n_taxa_data <- prop_results %>% 
  filter(variable == "n_stock") %>%
  select(eez_name,early,mid) %>% 
  left_join(n_trans_eez) %>% 
  # mutate(per = (early/n_trans)*100) %>% 
  mutate_at(vars(early,mid),
            .funs = ~(./n_trans)*100) %>% 
  rename(sf_eez_name = eez_name) %>% 
  left_join(Matching_names) %>% 
  select(sau_fishing_entity,fishing_entity_id,early,mid) %>% 
  gather("time_step","avrg_spp_per",early:mid) %>% 
  group_by(sau_fishing_entity,fishing_entity_id,time_step) %>%
  summarise(avrg_spp_per = mean(avrg_spp_per,na.rm=T)) %>% 
  mutate(time_step = ifelse(time_step == "early","per_early","per_mid")) %>%
  mutate(avrg_spp_per_100 = avrg_spp_per,
         avrg_spp_per = ifelse(avrg_spp_per > 50,50,avrg_spp_per)) %>% 
  filter(time_step == time_toplot)

# Included in map
n_taxa_map <- World_map %>% 
  full_join(n_taxa_data,
            by = c("sau_fishing_entity","fishing_entity_id")
  )

# Grey land
grey_land <- World_map %>% 
  filter(is.na(fishing_entity_id)) %>% 
  filter(!sovereignt %in% c("Antarctica"))

p <-
  ggplot() +
  geom_sf(data = World_eez_sf %>% 
  st_transform(crs = "+proj=eck4"), size = 0.1, fill = "white", col = "gray30") +
  geom_sf(data = subset(n_taxa_map, sovereignt != "Antarctica"),
          aes(fill = avrg_spp_per),
          size = 0.1,
          col = "white") +
  geom_sf(data = grey_land, size = 0.1, fill = "grey50", col = "gray30") +
  geom_sf(data = subset(sf_ready_plot, percentage >= 0), aes(color = percentage), size = 0.1, fill = "white") +
  geom_sf(data = point_data, aes(), color = "grey90") +
  geom_path(data = subset(arrows_data, percentage >= 0),
            aes(X, Y,
                group = group,
                col = percentage
            ),
            size = 1,
            arrow = arrow(length = unit(0.01, "npc"),
                          ends = "first"),
            show.legend = NA) +
  my_ggtheme_m(leg_pos = "bottom") +
  scale_color_gradientn(name= "Changes in catch proportion and changing stocks (%)",
                        colours = pal,
                        limits = c(0,max(sf_ready_plot$percentage,na.rm=T)),
                        breaks = seq(0,max(sf_ready_plot$percentage,na.rm=T),10),
                        labels = c(seq(0,max(sf_ready_plot$percentage-10,na.rm=T),10),">50")
  ) +
  scale_fill_gradientn(name= "Changes in catch proportion and changing stocks (%)",
                       colours = pal,
                       limits = c(0,max(sf_ready_plot$percentage,na.rm=T)),
                       breaks = seq(0,max(sf_ready_plot$percentage,na.rm=T),10),
                       labels = c(seq(0,max(sf_ready_plot$percentage-10,na.rm=T),10),">50")
  ) + guides(
    color=guide_colorbar(title.position="top")
  ) +
  theme(legend.key.width = unit(4,"line"))


# name <- paste0("./ssr_deep.png")
# Save figure
ggsave(plot =  p,
       name,
       width = 10,
       height = 5,
       units = "in")
```

# Straddling stocks Results


```{r}

```









