---
title: "Efectos del cambio climático en los stocks de peces transfronterizos de America del sur"
author: "Juliano Palacios-Abrantes"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(MyFunctions)

packages <- c(
  "readxl", # Read dataframe
  "data.table", # Read dataframe (Fast!)
  "tidyverse",
  "worrms",
  "sf",
  "sp"
)

my_lib(packages)

# Fix new updates of sf package
sf::sf_use_s2(use_s2 = FALSE)

source("../functions/get_results.R")
```

# GLobal data

```{r}
exploited_spp <- my_data("sau_species")

countries_sa <- c("Brazil","Uruguay","Falkland Isl. (UK)","Chile","Peru","Ecuador","Colombia (Pacific)","Colombia (Caribbean)","Venezuela","Suriname","Guyana","French Guiana")
```


# Transboundary stocks data

```{r}

# Transboundary species and their sharing EEZs (see Palacios-Abrantes et al; FishForVisa)
Transboundary_spp <- my_path("G", extra_path = "EmergingFish/Data/Species/", name="Transboundary_spp.csv", read = TRUE) %>% 
  clean_names()

# Neighbour list and their respective id (see chunk 3)
Neighbours <- my_path("G", extra_path = "EmergingFish/Data/Spatial/", name="Neighbours_eez_id.csv", read = TRUE)


all_results <- list()
# List of taxon to run 
taxon_list <- Transboundary_spp %>% 
  left_join(exploited_spp) %>% 
  pull(taxon_name) %>% 
  unique()

# Process in batches 'cus function does not like more than 50 species
# for (i in seq(1, length(taxon_list), by = 50)) {
#   batch <- taxon_list[i:min(i + 50 - 1, length(taxon_list))]
#   results <- wm_records_names(batch)
#   all_results <- append(all_results, results)
# }

# Re order dataset
# alphaid <- dplyr::bind_rows(all_results) %>%
#   dplyr::select(taxon_name = scientificname, status, aphia_id = valid_AphiaID,worms_name = valid_name,kingdom:genus) %>% 
#   # remove non-fish species (a.k.a. invertebrates, mammals...)
#     dplyr::filter(class %in% c("Elasmobranchii","Actinopterygii","Holocephali","Myxini",
#                                "Petromyzonti", "Actinopteri", "Teleostei", "Holostei",
#                                "Chondrostei")
#     ) %>% 
#   left_join(exploited_spp,
#             by = "taxon_name",
#             relationship = "many-to-many") 
  
  

# alphaid

# write_csv(
  # alphaid,
  # "south_america_spp.csv",
# )

alphaid <- read.csv("~/Library/CloudStorage/OneDrive-UBC/Data/MigrantFish/south_america_spp.csv")


# ------------------------------------------- #
### Estimate number of transboundary stocks ###
# ------------------------------------------- #

n_stock <-
  Transboundary_spp %>% 
  # Filter only fish
  filter(taxon_key %in% alphaid$taxon_key) %>% 
  left_join(Neighbours,
            by = c("eez_name", "eez_neighbour")) %>% 
  filter(eez_name %in% countries_sa) %>% 
  
  # left_join(exploited_spp) %>% 
  # filter(neighbour_id %in% c(1,105)) %>%
  # filter(neighbour_id == 470) %>%
  group_by(neighbour_id) %>%
  summarise(n_stock = length(unique(taxon_key))) %>%
  # View()
  group_by() %>% 
  summarise(t_trans_stocks = sum(n_stock)) %>% 
  pull(t_trans_stocks) # 373


ssr_data <- read_csv("~/Library/CloudStorage/OneDrive-UBC/Data/EmergingFish/Results/ssr_data.csv") %>% 
  filter(eez_name %in% c("Brazil","Uruguay","Falkland Isl. (UK)","Chile","Peru","Ecuador","Colombia (Pacific)","Colombia (Caribbean)","Venezuela","Suriname","Guyana","French Guiana"))

# Clean names to match data
Matching_names <- my_path("G","Spatial/SAU", "sau_matching_names.csv", read = T) %>% 
  rename(eezid = eez_id)

Taxon_list_emer <- list.files(my_path("G",extra_path = "/EmergingFish/Results/Emergence_2005"))

# clean names for function
Taxon_list_emer <- gsub("_.*","",Taxon_list_emer) 

# Filter out fish
# Filter paths that have distributions
Taxon_list_emer <- Taxon_list_emer[grepl(paste(alphaid$taxon_key, collapse = "|"), Taxon_list_emer)]


Paths <- paste(my_path("G",extra_path = "/EmergingFish/Results/Emergence_2005"),Taxon_list_emer,"_emergence.txt",sep="")

# Load all sp in one table
Eme_Res <- bind_rows(lapply(Paths, fread)) %>% 
  filter(
    n_ens == 10
  ) %>% 
  left_join(Neighbours,
            by = c("eez_name","eez_neighbour")
  ) %>% 
  rename(sf_eez_name=eez_name) %>% 
  left_join(Matching_names,
            by=  "sf_eez_name") %>% 
  clean_names() %>% 
  mutate(tresh = str_to_lower(tresh))  %>% 
    filter(sf_eez_name %in% c("Brazil","Uruguay","Falkland Isl. (UK)","Chile","Peru","Ecuador","Colombia (Pacific)","Colombia (Caribbean)","Venezuela","Suriname","Guyana","French Guiana"),
           eez_neighbour %in% c("Brazil","Uruguay","Falkland Isl. (UK)","Chile","Peru","Ecuador","Colombia (Pacific)","Colombia (Caribbean)","Venezuela","Suriname","Guyana","French Guiana")
           ) %>% 
  left_join(my_data("sau_species"))



unique(Eme_Res$common_name)

```


```{r}
# Global estimates
Eme_Res %>% 
  filter(emerging_yr >= 2030) %>% 
  group_by(tresh,neighbour_id) %>% 
  summarise(
    emerging_stocks = length(unique(taxon_key))
  ) %>% 
  group_by(tresh) %>% 
  summarise(
    emerging_stocks = sum(emerging_stocks),
    prop_total = (emerging_stocks/n_stock)*100,
  )
```
```{r}
# Per EEZs
Eme_Res %>% 
  filter(tresh == "tresh_two") %>% 
  # group_by() %>% 
  # summarise(meann_y = mean(emerging_yr,na_rm = T))
  group_by(sf_eez_name,eez_neighbour) %>% 
  summarise(
    n_total = n(),
    min_y = min(emerging_yr,na_rm = T),
    meann_y = mean(emerging_yr,na_rm = T)
  ) %>% 
  arrange(desc(n_total))


filter(taxon_key %in% alphaid$taxon_key)

```

```{r}


Sau_data <-fread(paste(my_path("G"),"EmergingFish/Data/SAU/sau_catch_value_country_taxon_JEPA.csv", sep ="")) %>%
  clean_names() %>% 
  # Remove high seas and 207 and 208 that are unknown
  filter(!fishing_entity_id %in% c(213,223)) %>%  # 207,208
  # Allocate catch of islands to UK
  mutate(fishing_entity_id = ifelse(fishing_entity_id %in% c(219,220), 183,fishing_entity_id)) %>% 
  # Convert to 2019 real USD
  mutate(values = 1.16 * value) %>%
  # Average 10 years of data
  group_by(fishing_entity_id,taxon_key) %>% 
  summarise_at(c("catch","value"),
               mean,na.rm=T) %>% 
  gather("variable","value",catch:value)


Eez_d_hist <- Eme_Res %>% 
  group_by(eezid,sau_fishing_entity,tresh) %>% 
  # summarise(n_tax = length(unique(taxon_key))) %>% 
  summarise(
    mean_yr = mean(emerging_yr,na.rm=T),
    sd_yr = sd(emerging_yr,na.rm=T),
    n_taxa = length(unique(taxon_key))
  ) %>% 
  gather("metric","value",mean_yr:n_taxa) %>% 
  # filter(metric != "n_taxa") %>% 
  mutate(
    reverse = abs(value-2100)  + 2000
  )



# Estimate the value (catch and USD) of emerging species
Eme_value_data <- Eme_Res %>% 
  group_by(sau_fishing_entity,fishing_entity_id,tresh,taxon_key) %>% 
  summarise(n()) %>% 
  left_join(Sau_data,
            by = c("fishing_entity_id","taxon_key")) %>% 
  filter(!is.na(variable)) %>% 
  group_by(sau_fishing_entity,fishing_entity_id,tresh,variable) %>% 
  summarise(
    sum_value = sum(value,na.rm=T),
    n_taxa = length(unique(taxon_key)) 
  )

# Total value of each fishing nation

Total_value <- Sau_data %>% 
  group_by(fishing_entity_id,variable) %>% 
  summarise(tot_value= sum(value,na.rm=T))


Value_map_data <- Eme_value_data %>% 
  left_join(Total_value,
            by = c("fishing_entity_id","variable")) %>% 
  mutate(participation = (sum_value/tot_value)*100+2000)


# Per fishing entity

fish_d_hist <- Eme_Res %>% 
  group_by(sau_fishing_entity,tresh) %>% 
  # summarise(n_tax = length(unique(taxon_key))) %>% 
  summarise(
    value = length(unique(taxon_key))
  ) %>% 
  filter(!is.na(sau_fishing_entity))



World_map <- rnaturalearth::ne_countries(scale = 'large', returnclass = c("sf")) %>%
  clean_names() %>% 
  select(iso_a3,sovereignt,sov_a3,name,name_long,region_wb,continent,geometry) %>% 
  st_transform(crs = "+proj=eck4") %>%
  # st_transform(crs = 4326) %>% # 4326
  mutate(iso_a3 = ifelse(sovereignt == "Norway","NOR",
                         ifelse(name == "France","FRA",
                                iso_a3)
  )
  )


World_map_nemer <- World_map %>%
  full_join(Value_map_data,
            by = c("sau_fishing_entity","fishing_entity_id")
  ) %>% 
  filter(!is.na(participation)) %>% 
  sf::st_transform(crs = "+proj=eck4") 


# These are regions without transboundary species
grey_land <- World_map %>% 
  filter(!fishing_entity_id %in% Value_map_data$fishing_entity_id) %>% 
  filter(!sovereignt %in% c("Antarctica"))%>% 
  sf::st_transform(crs = "+proj=eck4") 




```


